"""add transaction status

Revision ID: 6a66b838f888
Revises: 001
Create Date: 2026-07-08 17:49:12.286685

"""
from alembic import op
import sqlalchemy as sa


revision = '6a66b838f888'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "transactions",
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default="completed",
        ),
    )

    op.alter_column(
        "transactions",
        "status",
        server_default=None,
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'status')
    # ### end Alembic commands ###
